### ISSUE TITLE
Possibility to remove version number from banner?

### ISSUE THREAD

**Issue by fliespl** [ix-ai/smtp#16]
smtp_banner config name - how to change it?

**Comment by tlex** [comment]
Digging a bit through exim settings, you can:

* create a config file with the contents `smtp_banner = "Your text here"`
* mount that config file in the docker container under `/etc/exim4/_docker_additional_macros`

For example ([source](https://linux.goeszen.com/exim4-adding-a-smtp-banner-and-enabling-tls-for-mail-relay.html)):
```
smtp_banner = ${primary_hostname} ESMTP
```

See [entrypoint.sh#L110](https://github.com/ix-ai/smtp/blob/master/entrypoint.sh#L110) for details.
