### ISSUE TITLE
Persistance - what volumes?

### ISSUE THREAD

**Issue by fliespl** [ix-ai/smtp#17]
I can't find example as to which directories should be volumes to mount to server to keep message queue in case of restart.

Could this be added to documentation?

**Comment by fliespl** [comment]
@tlex Thank you for quick response. I am thinking...

Wouldn't it be a good idea to provide predefined VOLUME instruction in dockerfile the same way as mysql does for /var/lib/mysql or redis for /data? 

Just thinking out loud :)

**Comment by tlex** [comment]
Your suggestion completely went unnoticed in my inbox.

I'm more than happy to accept a pull/merge request for this :slightly_smiling_face: 

a.
