### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by abh** [ix-ai/smtp#24]
I upgraded my helm chart from using the namshi/smtp image to use this fork instead (thank you for maintaining it!)

If you think it's appropriate and useful, it might be worth linking to:

https://artifacthub.io/packages/helm/ntppool/smtp

**Comment by boomam** [comment]
@abh  Great to get stuff like this submitted, but you may want to update the chart so that it supports _all_ possible environment variables in the values.yaml.

**Comment by abh** [comment]
@boomam it does already. :-) I pushed a new version that clarifies that in the value.yaml comments.

**Comment by tlex** [comment]
Extremely late, but I've added now the link to the readme. Thanks for the work.
