### ISSUE TITLE
Relay as gmail is sending a copy to inbox

### ISSUE THREAD

**Issue by albgen** [ix-ai/smtp#35]
Hello,

i've tested to send an email using gmail as realy and it works but the problem is that i see a copy on my gmail inbox too.
Why is that? Any chance to disable this behaviour?

thank you

**Comment by tlex** [comment]
This is something that you will need to check in gmail. As far as I remember, gmail automatically copies all the messages sent in the "Sent" label.

The only workaround I can think of is creating a rule that filters those messages and archives or deletes

**Comment by albgen** [comment]
I don't think it has to do with gmail. I have tried another smtp software as relay and i don't any copy after sending.

**Comment by albgen** [comment]
Just checked the source code of the https://github.com/ix-ai/smtp/blob/master/entrypoint.sh
The address used for gmail is not the relay one, but the normal smtp used for client mail smtp.gmail.com
The address for relay is: smtp-relay.gmail.com

The difference is that if you use the smtp.gmail.com you have a lot of limits and one of the most restrictive is that you cannot send more than 100emails per day(amoung th fact that you find a copy on the sent folder)
While using the relay, you can up to 10k emails per day!

**Comment by albgen** [comment]
does not work even with  `SMARTHOST_ADDRESS`, `SMARTHOST_ALIASES`, `SMARTHOST_USER` and `SMARTHOST_PASSWORD`
This is the docker-compose file:
![image](https://github.com/ix-ai/smtp/assets/7231968/b360d9f3-f3cc-4b00-bb1a-27082d25deb7)

This is the error i see on the log:
![image](https://github.com/ix-ai/smtp/assets/7231968/9d02d590-6382-4203-b2cd-61a4ca4e8684)

Seems like the username and password are not copied on the right place...
