### ISSUE TITLE
Add the possibility to change the DKIM selector

### ISSUE THREAD

**Issue by Inglebard** [ix-ai/smtp#39]
Hello,

I use this container and I need to setup DKIM. Unfortunately, it is not possible for me to use "dkim" as DKIM selector.

It would be great if "DKIM_SELECTOR" can be change with docker variable.

The behavior to have a variable set or a fallback to "dkim" would be perfect.

**Comment by tlex** [comment]
Thanks for opening the feature request. I will target this for the coming weekend.

**Comment by tlex** [comment]
Just released [v0.7.0](https://gitlab.com/ix.ai/smtp/-/releases/v0.7.0) with support for `DKIM_SELECTOR`.

**Comment by Inglebard** [comment]
It works perfectly.

Thank you for the speed of the implementation and for your work.
