### ISSUE TITLE
Is it possible to forward incoming emails?

### ISSUE THREAD

**Issue by reza-akbari** [ix-ai/smtp#9]
Hi, thank you for maintaining this project.
I currently use this to only send emails, I was wondering if it's possible to also receive and forward incoming emails?
for example:
`info@mydomain.com` => forward => `myusername@gmail.com`
Thanks

**Comment by tlex** [comment]
Unfortunately, I know too little about how to set this up in exim. I hope there's a kind soul out there, that can give you the answer.

**Comment by reza-akbari** [comment]
I used [simple mail forwarder](https://github.com/huan/docker-simple-mail-forwarder)
